version: '3'
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-prod

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  fastapp:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: fastapp_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    container_name: celery_app
    env_file:
      - .env-prod
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: flower_app
    env_file:
      - .env-prod
    command: [ "/fastapi_app/docker/celery.sh", "flower" ]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555




