"""update operations

Revision ID: c67521a9d70b
Revises: ac6f0476e278
Create Date: 2023-04-03 13:55:43.839010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67521a9d70b'
down_revision = 'ac6f0476e278'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
